// The FLOOR PROJECTION: a static, MLA-owned mirror of the always-on floor block,
// rendered to `.claude/rules/<name>.generated.md` in the activated checkout so that
// write-capable SUBAGENTS (which never see the main session's UserPromptSubmit hook
// output) still inherit the governing floor. It is the SUPERSEDED fallback: the main
// session's live hook block (renderFloorRulesXml) is always the authoritative,
// current floor and explicitly supersedes this snapshot.
//
// notes/20260705-floor-rule-delivery-coverage-matrix.md, Phase 1. This module is PURE
// (render + parse + hash + ownership test only); all IO lives in the writer.
//
// Design invariants:
//   - Body-only hash. The `payloadHash` in the ownership header is sha256 over the
//     BODY (everything after the header comment), never the header itself. The header
//     carries the hash, so hashing the body keeps it stable and self-describing:
//     recompute sha256(body), compare to the declared hash -> owned iff they match.
//   - A manual edit to the body changes its hash, so an edited file no longer validates
//     as MLA-owned and the writer refuses to overwrite or delete it (Phase 1 spec).
//   - Floor-only body. The projection carries ONLY unconditional global floor rules
//     (isFloorRule); path-scoped / conditional / session rules are never projected.

import { createHash } from "node:crypto";
import { Directive } from "./types";
import { isFloorRule } from "./render";

// The deterministic on-disk location, relative to the activated checkout root
// (the .meetless.json marker dir), where `.claude/rules/` conventionally lives.
export const FLOOR_PROJECTION_RELPATH = ".claude/rules/meetless-mla-floor.generated.md";

// First line of the ownership header comment. A file that does not open with this
// exact sentinel is NOT an MLA projection and must never be overwritten or removed.
const OWNERSHIP_SENTINEL = "<!-- meetless-mla-floor-projection";

// Human title of the projection body. Kept out of the hash-affecting logic; changing
// copy here changes the body hash (a new projection version), which is intended.
const BODY_TITLE = "# MLA Governing Floor";

// The projection's own precedence self-identification: it announces that the live main
// hook block supersedes it. Mirrors the hook block's supersede sentence (Correction 4).
const BODY_PREAMBLE =
  "This is MLA's fallback floor snapshot for subagents. In the main session, the latest " +
  "complete MLA runtime floor block supersedes this snapshot.";

export interface ProjectionParts {
  header: string;
  body: string;
}

export function projectionBodyHash(body: string): string {
  return `sha256:${createHash("sha256").update(body, "utf8").digest("hex")}`;
}

// Render the floor-only markdown body from the deduped directive set. Returns the body
// text (title + supersede preamble + one bullet per floor rule) with a trailing newline,
// or "" when there are no eligible floor rules (nothing to project).
export function renderProjectionBody(dirs: Directive[]): string {
  const floor = dirs.filter(isFloorRule);
  if (!floor.length) return "";
  // A rule is a single line; collapse any stray newline so it stays one bullet.
  const bullets = floor.map((d) => `- ${d.text.trim().replace(/\s*\n\s*/g, " ")}`);
  return `${BODY_TITLE}\n\n${BODY_PREAMBLE}\n\n${bullets.join("\n")}\n`;
}

// Build the full file content: ownership header (bundle id + body hash) then the body.
// The header is an HTML comment that Claude Code strips before injection, so it is not
// model-facing; it exists purely as MLA's on-disk ownership marker. Returns "" when
// there is no floor content to project.
export function renderFloorProjection(dirs: Directive[], bundleId: string): string {
  const body = renderProjectionBody(dirs);
  if (!body) return "";
  const hash = projectionBodyHash(body);
  const header =
    `${OWNERSHIP_SENTINEL}\n` +
    `Generated by MLA from the governed rule bundle. Do not edit by hand.\n` +
    `bundleId: ${bundleId}\n` +
    `payloadHash: ${hash}\n` +
    `This HTML comment is MLA's on-disk ownership marker; it is expected to be stripped\n` +
    `at injection and is not model-facing. Editing the body below changes its hash, and\n` +
    `MLA then treats the file as user-owned and leaves it in place.\n` +
    `-->`;
  return `${header}\n${body}`;
}

// Split a file into its ownership header and body. Returns null when the content does
// not open with the MLA ownership sentinel or has no comment terminator (i.e. it is not
// a well-formed MLA projection). The body is everything after the header comment, minus
// the single newline the renderer inserts between them, so sha256(body) round-trips.
export function splitProjection(content: string): ProjectionParts | null {
  if (!content.startsWith(OWNERSHIP_SENTINEL)) return null;
  const close = content.indexOf("-->");
  if (close < 0) return null;
  const header = content.slice(0, close + 3);
  let body = content.slice(close + 3);
  if (body.startsWith("\n")) body = body.slice(1);
  return { header, body };
}

// The payloadHash declared in an existing header, or null when absent/malformed.
export function declaredPayloadHash(header: string): string | null {
  const m = header.match(/payloadHash:\s*(sha256:[0-9a-f]{64})/);
  return m ? m[1] : null;
}

// A file is an MLA-OWNED projection iff it opens with the ownership sentinel AND its
// body hashes to exactly the payloadHash its header declares. Any manual edit to the
// body breaks this equality, so an edited file reads as user-owned (not MLA-owned) and
// is left intact by the writer. An arbitrary user file (no sentinel) is never owned.
export function isOwnedProjection(content: string): boolean {
  const parts = splitProjection(content);
  if (!parts) return false;
  const declared = declaredPayloadHash(parts.header);
  if (!declared) return false;
  return declared === projectionBodyHash(parts.body);
}
