// src/lib/scanner/managed-rules.ts
//
// The mla-managed rule file: `.meetless/rules.md`. This is the local, mla-owned file of a
// repository's durable governed rules, materialized from the rules a human has accepted. The
// backend rule store is the source of truth; this file is a local artifact, and the scanner's
// prompt injection is served from the backend rule bundle, NOT from this file (see scan.ts,
// which skips this path). mla owns this file and only this file: it never edits a user's
// CLAUDE.md / AGENTS.md (preserving another tool's formatting is a maintenance trap). The file
// is rewritten in FULL from the accepted rule set, so updates are idempotent and ordering is
// deterministic by construction.
//
// Trust: a rule lands in this file only when a human accepts it, so every managed rule is
// `human_attested`. INV-AUTH-1: only accepted RULE objects become durable governed policy, and
// this file is where "accepted + durable" is recorded before it is published to the backend.
import { createHash } from "node:crypto";
import { Directive, Strength } from "./types";

export const MANAGED_RULES_PATH = ".meetless/rules.md";

// The header is regenerated verbatim every write. It tells a human reader (and a teammate
// reviewing the diff) what the file is, that mla owns it, and that the backend rule store is
// the source of truth this file is materialized from.
const MANAGED_HEADER = [
  "<!-- GENERATED BY mla. This is the mla-managed local file of this repository's durable",
  "     governed rules. The backend rule store is the source of truth; mla rewrites this file",
  "     in full from the accepted rule set, so do not hand-maintain it. Change a rule with",
  "     `mla`, not by editing here. -->",
  "# Repository rules",
].join("\n");

const REPO_WIDE_LABEL = "(repository-wide)";
const NO_SOURCES_LABEL = "(none)";

export interface ManagedRule {
  // Content-derived, stable across re-attest and independent of source: the same statement,
  // kind, and scope always hash to the same id, which is exactly what makes "re-attest the
  // same rule" idempotent and ordering deterministic. NOT derived from source, so the same
  // rule arriving from a second file dedupes to one row with the new source attached.
  id: string;
  statement: string; // normalized rule text (trimmed, internal whitespace collapsed)
  kind: "RULE"; // P0A only mints RULE
  strength: Strength;
  scope: string[]; // globs; empty = repository-wide. Sorted + deduped.
  sources: string[]; // provenance / evidence (e.g. "agent-memory:feedback_x.md"). Sorted + deduped.
}

function normalizeStatement(s: string): string {
  return s.trim().replace(/\s+/g, " ");
}

function uniqSorted(xs: readonly string[]): string[] {
  return [...new Set(xs.map((x) => x.trim()).filter(Boolean))].sort();
}

// The stable id: a pure function of the rule's IDENTITY (statement + kind + scope), never its
// source. A NUL (\u0000) separator between the three fields, and a SOH (\u0001) separator
// between scope entries, keep them from colliding (a scope of "ab" + statement ending "x" can
// never alias a statement ending "xab" with empty scope). These MUST stay as \uXXXX escapes,
// not raw control bytes: a literal 0x00/0x01 in the source makes the whole .ts file classify
// as binary, so grep/formatters silently skip it. The escapes compile to the identical bytes,
// so ids are unchanged.
export function managedRuleId(statement: string, kind: "RULE", scope: readonly string[]): string {
  const key = `${normalizeStatement(statement)}\u0000${kind}\u0000${uniqSorted(scope).join("\u0001")}`;
  return createHash("sha256").update(key).digest("hex").slice(0, 12);
}

export interface ManagedRuleInput {
  statement: string;
  strength?: Strength;
  scope?: readonly string[];
  sources?: readonly string[];
}

// Canonicalize raw input into a ManagedRule: normalize the statement, sort/dedupe scope and
// sources, default strength to the conservative SHOULD_FOLLOW (only an explicit MUST earns
// must-follow injection), and compute the stable id.
export function makeManagedRule(input: ManagedRuleInput): ManagedRule {
  const statement = normalizeStatement(input.statement);
  const scope = uniqSorted(input.scope ?? []);
  const kind = "RULE" as const;
  return {
    id: managedRuleId(statement, kind, scope),
    statement,
    kind,
    strength: input.strength === "MUST_FOLLOW" ? "MUST_FOLLOW" : "SHOULD_FOLLOW",
    scope,
    sources: uniqSorted(input.sources ?? []),
  };
}

function strengthRank(s: Strength): number {
  return s === "MUST_FOLLOW" ? 1 : 0;
}

// Idempotent add/update by stable id. Re-attesting the identical rule (same statement, kind,
// scope, strength, sources) is a structural no-op. A second source for an existing rule is
// merged into its evidence (exact-dedupe, memo Phase 1); the stronger strength wins so a rule
// promoted from SHOULD to MUST stays MUST. Input order otherwise preserved; render sorts.
export function upsertManagedRule(rules: readonly ManagedRule[], incoming: ManagedRule): ManagedRule[] {
  const idx = rules.findIndex((r) => r.id === incoming.id);
  if (idx === -1) return [...rules, incoming];
  const existing = rules[idx];
  const merged: ManagedRule = {
    ...existing,
    strength: strengthRank(incoming.strength) > strengthRank(existing.strength) ? incoming.strength : existing.strength,
    sources: uniqSorted([...existing.sources, ...incoming.sources]),
  };
  const next = [...rules];
  next[idx] = merged;
  return next;
}

// Fold a list of rules through upsert so any two that share an id (e.g. the same rule read
// from two copies of the file, or a hand-edit that duplicated a statement) collapse to one.
export function dedupeManagedRules(rules: readonly ManagedRule[]): ManagedRule[] {
  let out: ManagedRule[] = [];
  for (const r of rules) out = upsertManagedRule(out, r);
  return out;
}

// Deterministic full-file render: rules sorted by id, each a markdown block whose heading
// carries the (human-facing) id anchor and the statement, with the machine fields as a bullet
// list. Same rule set => byte-identical output, which is what makes writes idempotent.
export function renderManagedRules(rules: readonly ManagedRule[]): string {
  const sorted = dedupeManagedRules(rules).sort((a, b) => a.id.localeCompare(b.id));
  const blocks = sorted.map((r) => {
    const scope = r.scope.length ? r.scope.join(", ") : REPO_WIDE_LABEL;
    const sources = r.sources.length ? r.sources.join(", ") : NO_SOURCES_LABEL;
    return [
      `## [${r.id}] ${r.statement}`,
      "",
      `- strength: ${r.strength}`,
      `- scope: ${scope}`,
      `- sources: ${sources}`,
    ].join("\n");
  });
  return [MANAGED_HEADER, "", ...interleave(blocks)].join("\n") + "\n";
}

// Join blocks with a single blank line between them (and nothing trailing; the caller adds
// the final newline). Keeps the rendered file stable and diff-friendly.
function interleave(blocks: string[]): string[] {
  const out: string[] = [];
  blocks.forEach((b, i) => {
    if (i > 0) out.push("");
    out.push(b);
  });
  return out;
}

// Parse a managed rule file back into rules. Tolerant of hand-edits: the bracketed id in the
// heading is treated as a decorative anchor and IGNORED; the id is always recomputed from the
// parsed statement + kind + scope, so identity can never drift from content. Unknown bullet
// keys are ignored; a missing strength defaults to SHOULD_FOLLOW. Duplicate rules collapse.
export function parseManagedRules(text: string): ManagedRule[] {
  const lines = text.split("\n");
  const rules: ManagedRule[] = [];
  let current: { statement: string; strength?: Strength; scope: string[]; sources: string[] } | null = null;

  const flush = () => {
    if (!current) return;
    rules.push(makeManagedRule(current));
    current = null;
  };

  for (const line of lines) {
    const heading = /^##\s+(?:\[[0-9a-f]{6,}\]\s+)?(.+?)\s*$/.exec(line);
    if (heading) {
      flush();
      current = { statement: heading[1], scope: [], sources: [] };
      continue;
    }
    if (!current) continue;
    const bullet = /^\s*-\s+([a-zA-Z]+):\s*(.*)$/.exec(line);
    if (!bullet) continue;
    const key = bullet[1].toLowerCase();
    const value = bullet[2].trim();
    if (key === "strength") {
      current.strength = value === "MUST_FOLLOW" ? "MUST_FOLLOW" : "SHOULD_FOLLOW";
    } else if (key === "scope") {
      current.scope = value === REPO_WIDE_LABEL || value === "" ? [] : splitList(value);
    } else if (key === "sources" || key === "source") {
      current.sources = value === NO_SOURCES_LABEL || value === "" ? [] : splitList(value);
    }
  }
  flush();
  return dedupeManagedRules(rules);
}

function splitList(value: string): string[] {
  return value
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

// Convert managed rules into scanner directives. Every managed rule is human_attested (it is
// in the file only because a human accepted it), so a MUST_FOLLOW managed rule renders with
// must-follow authority in confirmedRulesXml. The directive id reuses the stable rule id.
export function managedRulesToDirectives(rules: readonly ManagedRule[], source = MANAGED_RULES_PATH): Directive[] {
  return dedupeManagedRules(rules).map((r) => ({
    id: r.id,
    text: r.statement,
    source,
    kind: "RULE" as const,
    strength: r.strength,
    attestation: "human_attested" as const,
    ...(r.scope.length ? { globs: r.scope } : {}),
  }));
}
