// test/commands/enrich-materialize.spec.ts
//
// End-to-end coverage for `mla enrich materialize`: the accepted-durable-rule -> managed
// file bridge actually writing `.meetless/rules.md` at the git root. These tests run the
// real command (runEnrich(["materialize", ...])) inside a throwaway git repo and assert
// against the file on disk, so they pin the load-bearing Phase 1 behaviors at the command
// boundary, not just in the pure helpers:
//   - a durable rule is written and the operator is told it is effective locally;
//   - accepting ONLY a decision writes NOTHING (INV-AUTH-2) -- the required Phase 1 test;
//   - --dry-run never touches disk;
//   - a malformed batch is refused whole (exit 2), leaving no partial file;
//   - re-materializing the same rule is byte-idempotent.
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runEnrich } from "../../src/commands/enrich";
import { MANAGED_RULES_PATH } from "../../src/lib/scanner/managed-rules";

function git(cwd: string, args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
}

// A valid documentation candidate (passes the same shape validator ingest uses: a file
// anchor is required for the documentation scout).
function docCandidate(kind: string, statement: string): Record<string, unknown> {
  return {
    kind,
    statement,
    sourceScout: "documentation",
    evidence: [{ type: "file", path: "CLAUDE.md", startLine: 1, endLine: 2 }],
  };
}

describe("mla enrich materialize (end to end, real file write)", () => {
  let repo: string;
  let root: string; // git toplevel (realpath); the command writes relative to this
  let managedPath: string;
  let acceptedFile: string;
  let cwd0: string;
  let logSpy: jest.SpyInstance;
  let errSpy: jest.SpyInstance;
  let out: string[];
  let err: string[];

  beforeEach(() => {
    repo = mkdtempSync(join(tmpdir(), "mla-materialize-"));
    git(repo, ["init", "-q"]);
    root = git(repo, ["rev-parse", "--show-toplevel"]);
    managedPath = join(root, MANAGED_RULES_PATH);
    acceptedFile = join(repo, "accepted.json");
    cwd0 = process.cwd();
    process.chdir(repo);
    out = [];
    err = [];
    logSpy = jest.spyOn(console, "log").mockImplementation((m?: unknown) => void out.push(String(m ?? "")));
    errSpy = jest.spyOn(console, "error").mockImplementation((m?: unknown) => void err.push(String(m ?? "")));
  });

  afterEach(() => {
    logSpy.mockRestore();
    errSpy.mockRestore();
    process.chdir(cwd0);
    rmSync(repo, { recursive: true, force: true });
  });

  function writeAccepted(candidates: unknown[]): void {
    writeFileSync(acceptedFile, JSON.stringify(candidates), "utf8");
  }

  it("writes an accepted durable rule into .meetless/rules.md and reports it effective locally", async () => {
    writeAccepted([docCandidate("constraint", "Use 127.0.0.1, not localhost, on macOS.")]);
    const code = await runEnrich(["materialize", "--accepted-file", acceptedFile]);
    expect(code).toBe(0);
    expect(existsSync(managedPath)).toBe(true);
    const text = readFileSync(managedPath, "utf8");
    expect(text).toContain("Use 127.0.0.1, not localhost, on macOS.");
    expect(text).toContain("GENERATED BY mla");
    expect(out.join("\n")).toMatch(/Effective locally\. Commit and push to share/);
  });

  // The required Phase 1 test (memo line 499): accepting a DECISION must not modify the
  // managed rules file. Here the file does not even get created.
  it("writes NOTHING when only a decision is accepted (INV-AUTH-2)", async () => {
    writeAccepted([docCandidate("decision", "We chose Postgres SKIP LOCKED over SQS.")]);
    const code = await runEnrich(["materialize", "--accepted-file", acceptedFile]);
    expect(code).toBe(0);
    expect(existsSync(managedPath)).toBe(false);
    expect(out.join("\n")).toMatch(/No durable rules to materialize/);
    expect(out.join("\n")).toMatch(/Skipped 1 non-rule candidate/);
  });

  it("leaves an existing managed file byte-identical when only a decision is accepted", async () => {
    writeAccepted([docCandidate("constraint", "Never commit secrets.")]);
    await runEnrich(["materialize", "--accepted-file", acceptedFile]);
    const before = readFileSync(managedPath, "utf8");

    writeAccepted([docCandidate("decision", "We picked Cloud Run over a VM.")]);
    const code = await runEnrich(["materialize", "--accepted-file", acceptedFile]);
    expect(code).toBe(0);
    expect(readFileSync(managedPath, "utf8")).toBe(before); // exact bytes
  });

  it("--dry-run reports the change without writing the file", async () => {
    writeAccepted([docCandidate("convention", "Prefer relative imports.")]);
    const code = await runEnrich(["materialize", "--accepted-file", acceptedFile, "--dry-run"]);
    expect(code).toBe(0);
    expect(existsSync(managedPath)).toBe(false);
    expect(out.join("\n")).toMatch(/Would materialize 1 durable rule/);
    expect(out.join("\n")).not.toMatch(/Effective locally/);
  });

  it("refuses the whole batch (exit 2) on a malformed candidate, writing no partial file", async () => {
    writeAccepted([
      docCandidate("constraint", "A good rule."),
      docCandidate("not-a-kind", "A bad rule."),
    ]);
    const code = await runEnrich(["materialize", "--accepted-file", acceptedFile]);
    expect(code).toBe(2);
    expect(existsSync(managedPath)).toBe(false);
    expect(err.join("\n")).toMatch(/refusing to materialize/);
    expect(err.join("\n")).toMatch(/bad_kind/);
  });

  it("is byte-idempotent: re-materializing the same accepted rule does not change the file", async () => {
    writeAccepted([docCandidate("boundary", "control owns the state machine.")]);
    await runEnrich(["materialize", "--accepted-file", acceptedFile]);
    const first = readFileSync(managedPath, "utf8");
    const code = await runEnrich(["materialize", "--accepted-file", acceptedFile]);
    expect(code).toBe(0);
    expect(readFileSync(managedPath, "utf8")).toBe(first);
  });

  it("exits 2 when the accepted payload is unreadable JSON, writing nothing", async () => {
    writeFileSync(acceptedFile, "{not json", "utf8");
    const code = await runEnrich(["materialize", "--accepted-file", acceptedFile]);
    expect(code).toBe(2);
    expect(existsSync(managedPath)).toBe(false);
    expect(err.join("\n")).toMatch(/not valid JSON/);
  });
});
