import { readFileSync } from "fs";
import { join } from "path";
import { redact, scanForSecrets, REDACTED } from "../../src/lib/redactor";
import { redactEventValue, redactEventBatch } from "../../src/commands/internal-redact-events";

// The "events" profile: the SEVEN required tests (ruling §7).
//
// What the profile is. Same literal credential patterns as "full", same entropy
// bar as "full" (2 character classes, 3.5 bits), plus ONE exemption: a
// path-shaped token (contains a slash, contains lowercase, contains NO
// uppercase) is not eaten by the entropy sweep. Exactly one production caller,
// `mla _internal redact-events`, the flush-time boundary for the hook spool.
//
// Why it is a third profile and not a loosening of "full". "full" is three
// things at once: the at-rest default, the block-on-detect scanner's bar, and
// the fallback for an unrecognized profile name. Relaxing it would relax all
// three, silently, for callers that never asked. Test 3 and test 4 are the ones
// that prove that did not happen.
//
// The measurement these tests are built on lives in
// test/fixtures/redaction-path-corpus.json, regenerated by
// scripts/measure-redaction-corpus.js against a real transcript corpus. It is
// frozen deliberately: the live corpus grows every session, so a test that
// re-measured would never be deterministic.

interface PathCorpus {
  transcripts: number;
  distinctTokens: number;
  totalOccurrences: number;
  tokens: Record<string, number>;
}

const CORPUS: PathCorpus = JSON.parse(
  readFileSync(join(__dirname, "..", "fixtures", "redaction-path-corpus.json"), "utf8"),
);

// Fake values in real formats. No live credential ever enters a fixture.
const CREDENTIAL_FIXTURES: Array<{ name: string; input: string; secret: string }> = [
  {
    name: "openai_project_key",
    input: "curl -H 'Authorization: Bearer sk-proj-AbCdEfGhIjKlMnOpQrStUv' https://api.openai.com",
    secret: "sk-proj-AbCdEfGhIjKlMnOpQrStUv",
  },
  {
    name: "github_pat",
    input: "git remote set-url origin https://gh" + "p_AbCdEfGhIjKlMnOpQrStUvWxYz0123456789@github.com/x/y",
    secret: "gh" + "p_AbCdEfGhIjKlMnOpQrStUvWxYz0123456789",
  },
  {
    name: "github_fine_grained_pat",
    input: "export TOKEN=github_pat_11ABCDEFG0abcdefghijkl_AbCdEfGhIjKlMnOpQrStUvWxYz",
    secret: "github_pat_11ABCDEFG0abcdefghijkl_AbCdEfGhIjKlMnOpQrStUvWxYz",
  },
  {
    name: "slack_bot_token",
    input: "SLACK_BOT_TOKEN=xox" + "b-1234567890-0987654321-AbCdEfGhIjKlMnOpQrSt",
    secret: "xox" + "b-1234567890-0987654321-AbCdEfGhIjKlMnOpQrSt",
  },
  {
    name: "aws_access_key_id",
    input: "aws configure set aws_access_key_id AKIA" + "IOSFODNN7EXAMPLE",
    secret: "AKIA" + "IOSFODNN7EXAMPLE",
  },
  {
    name: "google_api_key",
    input: "AIzaSyA1bC2dE3fG4hI5jK6lM7nO8pQ9rS0tU1vW",
    secret: "AIzaSyA1bC2dE3fG4hI5jK6lM7nO8pQ9rS0tU1vW",
  },
  {
    name: "jwt",
    input: "cookie set to eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NSJ9.dBjftJeZ4CVPmB92K27uhbUJU1p1r_wW1gFWFOEjXk",
    secret: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NSJ9.dBjftJeZ4CVPmB92K27uhbUJU1p1r_wW1gFWFOEjXk",
  },
  {
    name: "basic_auth",
    input: "curl -H 'Authorization: Basic ZGV2Omh1bnRlcjI=' https://example.test",
    secret: "ZGV2Omh1bnRlcjI=",
  },
  {
    name: "env_assignment_value",
    input: "OPENAI_API_KEY=sk-AbCdEfGhIjKlMnOpQrStUvWx",
    secret: "sk-AbCdEfGhIjKlMnOpQrStUvWx",
  },
  {
    name: "anthropic_key",
    input: "ANTHROPIC_API_KEY='sk-ant-api03-abcdefghijklmnopqrstuvwx'",
    secret: "sk-ant-api03-abcdefghijklmnopqrstuvwx",
  },
  {
    name: "huggingface_token",
    input: "hf_AbCdEfGhIjKlMnOpQrStUvWxYz012345",
    secret: "hf_AbCdEfGhIjKlMnOpQrStUvWxYz012345",
  },
  {
    name: "cookie_header",
    input: "Cookie: session=abc123def456ghi789; other=x",
    secret: "session=abc123def456ghi789",
  },
  {
    name: "private_key_block",
    input:
      "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAoP1aBcDeFgHiJkLmNoPqRsTuVwXyZ\n-----END RSA PRIVATE KEY-----",
    secret: "MIIEowIBAAKCAQEAoP1aBcDeFgHiJkLmNoPqRsTuVwXyZ",
  },
  {
    name: "bare_base64_blob",
    // No prefix, no key name. This one is caught by the ENTROPY bar alone, which
    // is exactly the half the events profile touches, so it is the fixture that
    // matters most here.
    input: "the value was wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY1234 and it failed",
    secret: "wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY1234",
  },
];

describe("events profile, test 1: the measured corpus survives", () => {
  // The whole reason the profile exists. If this drops, the ledger `mla review`
  // reasons over goes back to being unable to say which file a command touched.
  it("preserves every path-shaped span the full bar destroys", () => {
    const tokens = Object.keys(CORPUS.tokens);
    expect(tokens.length).toBe(CORPUS.distinctTokens);

    const eaten = tokens.filter((t) => redact(t, "events") !== t);
    // Name the survivors, not the count, so a failure says WHICH shape regressed.
    expect(eaten).toEqual([]);
  });

  it("accounts for all 8,909 measured occurrences, not just the distinct shapes", () => {
    // Weighted by how often each token actually appeared. A profile that saved
    // 1,574 rare shapes and dropped the single most frequent one would pass the
    // test above and still gut the corpus.
    const preserved = Object.entries(CORPUS.tokens)
      .filter(([t]) => redact(t, "events") === t)
      .reduce((sum, [, n]) => sum + n, 0);

    expect(preserved).toBe(CORPUS.totalOccurrences);
    expect(preserved).toBe(8909);
  });

  it("confirms the fixture is a record of real damage: the full bar eats all of it", () => {
    // Without this, test 1 could pass against a fixture of tokens that were never
    // at risk, and prove nothing at all.
    const survivingUnderFull = Object.keys(CORPUS.tokens).filter((t) => redact(t, "full") === t);
    expect(survivingUnderFull).toEqual([]);
  });
});

describe("events profile, test 2: every literal credential still goes", () => {
  it.each(CREDENTIAL_FIXTURES)("redacts $name under events", ({ input, secret }) => {
    const out = redact(input, "events") as string;
    expect(out).not.toContain(secret);
    expect(out).toContain(REDACTED);
  });

  it("redacts every fixture identically to full, because only the path shape moved", () => {
    for (const { name, input } of CREDENTIAL_FIXTURES) {
      expect({ name, out: redact(input, "events") }).toEqual({
        name,
        out: redact(input, "full"),
      });
    }
  });

  it("keeps the env var NAME while dropping the value, same as full", () => {
    const out = redact("OPENAI_API_KEY=sk-AbCdEfGhIjKlMnOpQrStUvWx", "events") as string;
    expect(out).toBe(`OPENAI_API_KEY=${REDACTED}`);
  });
});

describe("events profile, test 3: the global full profile did not move", () => {
  // The test that proves relaxing "events" did not relax the at-rest default.
  // Synthetic, like the corpus: the assertions read this token's SHAPE (lowercase,
  // a separator, >=32 chars, 2 classes, entropy over the bar), never its text, so
  // naming a real private source file bought nothing and shipped the tree layout.
  const PATH_SHAPED = "svc/example/src/quorum-ledger/quorum-ledger-projection";

  it("still redacts the path-shaped token that events now exempts", () => {
    expect(redact(PATH_SHAPED, "full")).toBe(REDACTED);
    expect(redact(PATH_SHAPED, "events")).toBe(PATH_SHAPED);
  });

  it("still redacts it when no profile is passed at all", () => {
    // The default argument is the at-rest bar. If a future refactor made
    // "events" the default, every other test here would still pass.
    expect(redact(PATH_SHAPED)).toBe(REDACTED);
  });

  it("leaves the retrieval bar untouched", () => {
    // retrieval requires 3 classes; this token has lower + separator only, so it
    // survives there for a completely different reason than the path exemption.
    expect(redact(PATH_SHAPED, "retrieval")).toBe(PATH_SHAPED);
    const mixed = "AbCdEf0123456789GhIjKlMnOpQrStUvWxYz0123";
    expect(redact(mixed, "retrieval")).toBe(REDACTED);
    expect(redact(mixed, "full")).toBe(REDACTED);
  });
});

describe("events profile, test 4: the block-on-detect file scanner is unchanged", () => {
  // scanForSecrets gates a FILE leaving the machine. A false positive costs one
  // blocked upload; a false negative costs a live credential. It hardcodes the
  // "full" bar and must never acquire a profile parameter.
  it("still blocks a file whose only finding is a path-shaped high-entropy token", () => {
    const token = "svc/example/src/quorum-ledger/quorum-ledger-projection";
    expect(scanForSecrets(token)).toContain("high_entropy_token");
  });

  it("still blocks the literal credential fixtures", () => {
    for (const { name, input } of CREDENTIAL_FIXTURES) {
      expect({ name, clean: scanForSecrets(input).length === 0 }).toEqual({ name, clean: false });
    }
  });

  it("takes no profile argument, so no caller can weaken it", () => {
    // Arity is the enforcement. A second parameter is the exact change this
    // test exists to catch.
    expect(scanForSecrets.length).toBe(1);
  });
});

describe("events profile, test 5: the accepted residual, written down as the price", () => {
  // A lowercase + digit + slash secret matches the path signature and passes.
  // This is NOT hidden and NOT argued away. "Path-shaped" is a signature, not a
  // proof of innocence, and the arithmetic about how rarely a random generator
  // lands in this shape is a statement about generators, not a security
  // property.
  //
  // The exposure is bounded to the events spool: the same token is still
  // redacted at rest under "full" everywhere else, including by the file
  // scanner (asserted below), so it never becomes a stored credential.
  const SYNTHETIC_RESIDUAL = "k7v2m9x4q1w8/n5b3j6h0z2c7r4t9y1p8s5d3f6g0";

  it("matches the path signature", () => {
    expect(SYNTHETIC_RESIDUAL).toContain("/");
    expect(/[a-z]/.test(SYNTHETIC_RESIDUAL)).toBe(true);
    expect(/[A-Z]/.test(SYNTHETIC_RESIDUAL)).toBe(false);
  });

  it("SURVIVES the events profile: this is the accepted residual", () => {
    expect(redact(SYNTHETIC_RESIDUAL, "events")).toBe(SYNTHETIC_RESIDUAL);
  });

  it("is still redacted at rest under full, which bounds the exposure", () => {
    expect(redact(SYNTHETIC_RESIDUAL, "full")).toBe(REDACTED);
    expect(scanForSecrets(SYNTHETIC_RESIDUAL)).toContain("high_entropy_token");
  });

  it("still goes under events the moment any uppercase appears", () => {
    // The no-uppercase clause is what keeps the exemption away from base64, and
    // base64 is the shape of an AWS secret access key.
    const withUpper = "k7v2m9x4q1w8/n5b3j6h0z2c7r4t9y1p8s5d3f6G0";
    expect(redact(withUpper, "events")).toBe(REDACTED);
  });

  it("still goes under events when a literal pattern recognizes it", () => {
    // The exemption only ever bypasses the ENTROPY sweep. Literal credential
    // patterns run first and are identical across all three profiles.
    const literalInPathShape = "gh" + "p_abcdefghijklmnopqrstuvwxyz0123456789/x";
    expect(redact(literalInPathShape, "events")).toContain(REDACTED);
  });
});

describe("events profile, test 6: parity across the planes", () => {
  // HONEST SCOPE, and the reason this test does not look like the other parity
  // specs. Profiles exist on TWO of the four planes:
  //
  //   packages/cli/src/lib/redactor.ts    profile-bearing (full/retrieval/events)
  //   packages/ask-core/redactor.js       profile-bearing (mirrored, ESM)
  //   apps/control/src/core/services/redactor.ts   NO profile parameter
  //   intel/app/observability/redaction.py         NO profile parameter
  //
  // That asymmetry is pre-existing: "retrieval" has the same shape, because the
  // two profile-less planes are at-rest surfaces with no caller that would ever
  // want a weaker bar. Adding profile machinery there would create exactly the
  // thing we do not want, a way for a future control caller to weaken at-rest
  // redaction.
  //
  // So parity for "events" is locked as: the two profile-bearing planes agree
  // byte-for-byte (asserted in packages/ask-core/redactor.test.js against this
  // same fixture list), and the two profile-less planes CANNOT be asked for it
  // and continue to apply the full bar (asserted in their own parity specs by
  // the path-shaped token from test 3, which they must still redact).
  const CROSS_PLANE_CASES = [
    "apps/control/src/coordination-case/coordination-case-projection",
    "packages/control-db/prisma/migrations/20260722180000_add_reconciliation_disposition_reference_rows",
    "k7v2m9x4q1w8/n5b3j6h0z2c7r4t9y1p8s5d3f6g0",
    "OPENAI_API_KEY=sk-AbCdEfGhIjKlMnOpQrStUvWx",
    "wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY1234",
  ];

  it("pins the cross-plane expectations the ask-core mirror asserts too", () => {
    // Mirror of EVENTS_PARITY_CASES in packages/ask-core/redactor.test.js.
    // Change one, change both IN THE SAME COMMIT.
    expect(CROSS_PLANE_CASES.map((c) => redact(c, "events"))).toEqual([
      "apps/control/src/coordination-case/coordination-case-projection",
      "packages/control-db/prisma/migrations/20260722180000_add_reconciliation_disposition_reference_rows",
      "k7v2m9x4q1w8/n5b3j6h0z2c7r4t9y1p8s5d3f6g0",
      `OPENAI_API_KEY=${REDACTED}`,
      REDACTED,
    ]);
  });

  it("pins what the two profile-less planes must still do with the same inputs", () => {
    // Their bar is "full", unconditionally. This is the assertion their own
    // parity specs mirror; if this list changes, theirs must change with it.
    expect(CROSS_PLANE_CASES.map((c) => redact(c, "full"))).toEqual([
      REDACTED,
      REDACTED,
      REDACTED,
      `OPENAI_API_KEY=${REDACTED}`,
      REDACTED,
    ]);
  });
});

describe("events profile, test 7: the real caller requests it on the wire", () => {
  // Not "is capable of requesting it". The actual production path, exercised.
  it("preserves a path through the real redactEventValue", () => {
    const p = "apps/control/src/coordination-case/coordination-case-projection";
    expect(redactEventValue(p, "command")).toBe(p);
  });

  it("proves the caller is not merely relying on a STRUCTURAL_KEYS allowlist entry", () => {
    // "command" is deliberately NOT in STRUCTURAL_KEYS: it is free text and must
    // be redacted. The path survives because of the PROFILE, not because the key
    // was exempted. Under an un-profiled redactor this same call would return
    // "[REDACTED]", which is what the assertion below rules out.
    const p = "apps/control/src/coordination-case/coordination-case-projection";
    expect(redact(p, "full")).toBe(REDACTED);
    expect(redactEventValue(p, "command")).toBe(p);
  });

  it("redacts a credential in the same field, in the same call", () => {
    const cmd = "cd apps/control/src/coordination-case && GH_TOKEN=ghp_AbCdEfGhIjKlMnOpQrStUvWxYz01 pnpm test";
    const out = redactEventValue(cmd, "command") as string;
    expect(out).not.toContain("ghp_AbCdEfGhIjKlMnOpQrStUvWxYz01");
    expect(out).toContain("apps/control/src/coordination-case");
    expect(out).toContain("GH_TOKEN=");
  });

  it("runs the profile through the real batch boundary, end to end", () => {
    // The shape flush.sh actually pipes through `mla _internal redact-events`.
    const batch = [
      {
        eventKey: "evt-1",
        eventType: "tool_used_bash",
        occurredAt: "2026-07-27T00:00:00.000Z",
        payload: {
          command:
            "node scripts/measure-redaction-corpus.js && export SLACK_BOT_TOKEN=xox" + "b-1234567890-0987654321-AbCdEfGhIjKlMnOpQrSt",
          stdout: "wrote apps/control/src/coordination-case/coordination-case-projection",
          exitCode: 0,
          sessionId: "0199f1e0-9c1a-7c3e-b0a1-2f4d6e8a0b2c",
        },
      },
    ];

    const [out] = redactEventBatch(batch) as Array<{
      eventKey: string;
      payload: Record<string, unknown>;
    }>;

    expect(out.eventKey).toBe("evt-1");
    // The credential is gone.
    expect(out.payload.command).not.toContain("xox" + "b-1234567890-0987654321-AbCdEfGhIjKlMnOpQrSt");
    // The paths that make the ledger readable are NOT.
    expect(out.payload.command).toContain("scripts/measure-redaction-corpus.js");
    expect(out.payload.stdout).toContain(
      "apps/control/src/coordination-case/coordination-case-projection",
    );
    // Structural fields pass through untouched.
    expect(out.payload.exitCode).toBe(0);
    expect(out.payload.sessionId).toBe("0199f1e0-9c1a-7c3e-b0a1-2f4d6e8a0b2c");
  });

  it("is the ONLY production caller of the events profile", () => {
    // Grep-equivalent, enforced. A second caller means the profile has stopped
    // being a scoped exemption for one ledger and become a general weakening.
    const root = join(__dirname, "..", "..", "src");
    const { execFileSync } = require("child_process") as typeof import("child_process");
    let hits: string[] = [];
    try {
      hits = execFileSync("grep", ["-rlE", `redact\\([^)]*["']events["']`, root], {
        encoding: "utf8",
      })
        .trim()
        .split("\n")
        .filter(Boolean);
    } catch (e: unknown) {
      // grep exits 1 on no match, which would itself be a failure here.
      const status = (e as { status?: number }).status;
      if (status !== 1) throw e;
    }
    expect(hits.map((h) => h.replace(`${root}/`, ""))).toEqual([
      "commands/internal-redact-events.ts",
    ]);
  });
});
