#!/usr/bin/env bash
# render-cask.sh: emit the Homebrew cask Ruby for `mla` to stdout.
#
# Usage:  homebrew/render-cask.sh <version> <release-dir>
#   version      release version, with or without a leading v (normalized to bare)
#   release-dir  dir holding the macOS archives' .sha256 sidecars:
#                  mla-aarch64-apple-darwin.tar.gz.sha256   (Apple Silicon)
#                  mla-x86_64-apple-darwin.tar.gz.sha256    (Intel)
#
# The cask is dual-arch: one `url` template interpolates the per-machine triple
# (the `arch` stanza), and on_arm/on_intel carry the matching sha256. The URL
# pattern and triples MUST stay byte-identical to install.sh's resolve_url so
# both install paths fetch the exact same assets.
#
# This is intentionally a self-contained renderer, not a GoReleaser config: we
# build binaries with @yao-pkg/pkg (build-release.sh), not GoReleaser, so the
# cask is the only thing GoReleaser would own here. A pure renderer is hermetic,
# unit-testable, and has no extra toolchain dependency.
#
# Env overrides (CI sets none; defaults match the published install one-liners):
#   MLA_DOWNLOAD_URL  base url for release archives. MUST equal install.sh's
#                     DOWNLOAD_BASE so the cask and the curl installer pull the
#                     exact same assets. Default: the public meetless-public GCS
#                     bucket, the canonical release host. brew fetches it
#                     anonymously with no GitHub auth, so the cask url must point
#                     at the bucket, not a github.com releases path.
set -euo pipefail

VERSION="${1:-}"
RELEASE_DIR="${2:-}"
DOWNLOAD_BASE="${MLA_DOWNLOAD_URL:-https://storage.googleapis.com/meetless-public/cli/releases}"

if [ -z "$VERSION" ] || [ -z "$RELEASE_DIR" ]; then
  echo "render-cask: error: usage: render-cask.sh <version> <release-dir>" >&2
  exit 2
fi
VERSION="${VERSION#v}"   # accept 0.4.2 or v0.4.2; the cask version is bare

[ -d "$RELEASE_DIR" ] || { echo "render-cask: error: no release dir '$RELEASE_DIR'" >&2; exit 1; }

# read just the hex out of a "<hex>  <filename>" sidecar (install.sh's contract).
read_sha() {  # $1=triple
  _f="$RELEASE_DIR/mla-$1.tar.gz.sha256"
  [ -f "$_f" ] || { echo "render-cask: error: missing checksum $_f" >&2; exit 1; }
  _hex="$(cut -d' ' -f1 < "$_f")"
  # a sha256 is 64 lowercase hex chars; refuse anything else so a malformed
  # sidecar fails the release instead of shipping a cask brew will reject.
  if ! printf '%s' "$_hex" | grep -Eq '^[0-9a-f]{64}$'; then
    echo "render-cask: error: $_f does not hold a 64-char sha256 ('$_hex')" >&2
    exit 1
  fi
  printf '%s' "$_hex"
}

ARM_SHA="$(read_sha aarch64-apple-darwin)"

# Intel is OPTIONAL. The release matrix currently drops the macos-x64 build
# (see release-cli.yml: the GitHub macos-13 queue stalled a release), so its
# sidecar may be absent. When it is, emit an arm-only cask that matches what the
# release actually shipped (and what install.sh can resolve) instead of failing
# the whole release on a missing Intel checksum. Re-adding the macos-x64 matrix
# entry restores the dual-arch cask automatically, no change needed here.
INTEL_SIDECAR="$RELEASE_DIR/mla-x86_64-apple-darwin.tar.gz.sha256"
if [ -f "$INTEL_SIDECAR" ]; then
  INTEL_SHA="$(read_sha x86_64-apple-darwin)"
fi

CASK_HEADER=$(cat <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by meetless-cli/homebrew/render-cask.sh on each release.
# Do not edit by hand; edits are overwritten on the next version bump.
EOF
)

CASK_CAVEATS=$(cat <<'EOF'
  binary "mla"

  caveats <<~CAVEATS
    The mla command is now on your PATH via Homebrew.
    Get started:  mla --help
  CAVEATS
end
EOF
)

if [ -n "${INTEL_SHA:-}" ]; then
  # Dual-arch: one url template with the #{arch} triple, per-arch sha256.
  cat <<EOF
$CASK_HEADER
cask "mla" do
  arch arm: "aarch64-apple-darwin", intel: "x86_64-apple-darwin"

  version "$VERSION"

  on_arm do
    sha256 "$ARM_SHA"
  end
  on_intel do
    sha256 "$INTEL_SHA"
  end

  url "$DOWNLOAD_BASE/download/v#{version}/mla-#{arch}.tar.gz"
  name "Meetless CLI"
  desc "Change-governance CLI (mla) for product delivery"
  homepage "https://meetless.ai"

$CASK_CAVEATS
EOF
else
  # Arm-only: no arch stanza, the triple is hard-coded into the url. brew on an
  # Intel mac will report mla as unavailable, which is the truth until the
  # macos-x64 build is re-enabled.
  cat <<EOF
$CASK_HEADER
cask "mla" do
  version "$VERSION"

  sha256 "$ARM_SHA"

  url "$DOWNLOAD_BASE/download/v#{version}/mla-aarch64-apple-darwin.tar.gz"
  name "Meetless CLI"
  desc "Change-governance CLI (mla) for product delivery"
  homepage "https://meetless.ai"

  depends_on arch: :arm64

$CASK_CAVEATS
EOF
fi
