// test/hooks/injection-trace-actor-attribution.spec.ts
//
// WHO injected? `injection_traces.actorId` answers that, and on 2026-08-09 it was
// NULL on all 1,897 production rows.
//
// The failure is not in the schema, the contract, or the writer. All three handle
// the field: schema.prisma declares `actorId String? // workspace member, when
// known`, injection-trace.contract.ts parses `asString(p.actorId)`, and
// agent-run.service.ts writes `actorId: v.actorId`. Every one of them is correct
// and every one of them has been storing `undefined -> null` since the column
// existed, because the PRODUCERS -- the two bash hooks that mint the spool line --
// never put the key in the payload. A structurally complete, inert component.
//
// Per-user attribution has worked anyway, by accident: every workspace carrying
// traces has exactly one member, so `workspaceId` implies the human. The first
// two-person workspace silently breaks it. Nothing errors; the rows just become
// unattributable, or get split across members by whatever tiebreak the reader
// invented that day.
//
// These specs pin the PRODUCER side, where the gap is, on both surfaces:
//   - user-prompt-submit.sh spool_injection_trace()  -> sourceSurface HOOK
//   - post-tool-use.sh MCP evidence-pull branch      -> sourceSurface MCP
//
// They drive the REAL scripts under src/hooks-template/ with a real bash and
// assert on the bytes actually written to the spool, never against a copy of the
// script pasted into a TS literal (see home-guard.spec.ts for why that proves
// nothing).
//
// The third case is the one that keeps this honest: a logged-out CLI has no actor,
// and the field must come out as an explicit `null`, never `""` and never a
// fabricated machine id. `actorId` means "a workspace member we can name"; an
// empty string would be a lie the console cannot detect.
import { spawn } from "node:child_process";
import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const HOOKS = join(__dirname, "..", "..", "src", "hooks-template");
const UPS_SH = join(HOOKS, "user-prompt-submit.sh");
const PTU_SH = join(HOOKS, "post-tool-use.sh");
const CLI = join(__dirname, "..", "..", "dist", "cli.js");

// The hooks shell out to the BUILT cli (`$MLA_PATH _internal ...`), so these need
// dist/. Skip rather than silently pass on an unbuilt tree.
const describeIfBuilt = existsSync(CLI) ? describe : describe.skip;

const SID = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
const WORKSPACE = "ws_actor_attribution_spec";
const ACTOR = "wu_actor_attribution_spec";

interface Wire {
  port: number;
  close: () => Promise<void>;
}

async function startWire(body: string): Promise<Wire> {
  const server: Server = createServer((req: IncomingMessage, res: ServerResponse) => {
    req.resume();
    req.on("end", () => {
      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(body);
    });
  });
  await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
  const addr = server.address();
  return {
    port: typeof addr === "object" && addr ? addr.port : 0,
    close: () => new Promise<void>((resolve) => server.close(() => resolve())),
  };
}

/**
 * An isolated ~/.meetless. common.sh honors an ABSOLUTE MEETLESS_HOME ahead of
 * $HOME, which keeps these specs off the operator's real state tree and off the
 * shared cli-config that concurrent sessions read.
 *
 * `actorUserId: null` models the logged-out CLI: `mla login` is what writes that
 * key, so before it (or after `mla logout`) the config simply lacks an actor.
 */
function makeHome(opts: {
  controlUrl: string;
  intelUrl: string;
  mlaPath: string;
  actorUserId: string | null;
}): string {
  const home = mkdtempSync(join(tmpdir(), "ml-actor-home-"));
  mkdirSync(join(home, "queue"), { recursive: true });
  writeFileSync(
    join(home, "cli-config.json"),
    JSON.stringify({
      controlUrl: opts.controlUrl,
      intelUrl: opts.intelUrl,
      mlaPath: opts.mlaPath,
      ...(opts.actorUserId ? { actorUserId: opts.actorUserId } : {}),
      auth: { mode: "user-token", accessToken: "test-access-token" },
    }),
  );
  return home;
}

let stubSeq = 0;
function makeMlaStub(dir: string, passthrough: string[]): string {
  const p = join(dir, `mla-stub-${++stubSeq}.sh`);
  writeFileSync(
    p,
    [
      "#!/usr/bin/env bash",
      "# generated by test/hooks/injection-trace-actor-attribution.spec.ts",
      'sub="${2:-}"',
      'case "$sub" in',
      `  ${passthrough.map((x) => `'${x}'`).join("|")}) exec node ${JSON.stringify(CLI)} "$@" ;;`,
      "  *) exit 0 ;;",
      "esac",
      "",
    ].join("\n"),
  );
  chmodSync(p, 0o755);
  return p;
}

function runHook(
  script: string,
  home: string,
  opts: { cwd?: string; input?: string; env?: Record<string, string> } = {},
): Promise<{ status: number | null; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn("bash", [script], {
      env: {
        PATH: process.env.PATH ?? "/usr/bin:/bin",
        HOME: process.env.HOME ?? tmpdir(),
        MEETLESS_HOME: home,
        ...(opts.env ?? {}),
      },
      cwd: opts.cwd ?? tmpdir(),
    });
    let stdout = "";
    let stderr = "";
    child.stdout.setEncoding("utf8");
    child.stderr.setEncoding("utf8");
    child.stdout.on("data", (c) => (stdout += c.toString()));
    child.stderr.on("data", (c) => (stderr += c.toString()));
    child.on("error", reject);
    child.on("close", (status) => resolve({ status, stdout, stderr }));
    if (opts.input !== undefined) child.stdin.write(opts.input);
    child.stdin.end();
  });
}

/** Every injection_trace line the hooks spooled this run. */
function injectionTraces(home: string): Array<Record<string, any>> {
  const f = join(home, "queue", `${SID}.jsonl`);
  if (!existsSync(f)) return [];
  return readFileSync(f, "utf8")
    .split("\n")
    .filter((l) => l.trim())
    .map((l) => {
      try {
        return JSON.parse(l);
      } catch {
        return null;
      }
    })
    .filter((e): e is Record<string, any> => !!e && e.event === "injection_trace");
}

describeIfBuilt("injection_traces.actorId: the producers must name the actor", () => {
  let intel: Wire;
  let stubDir: string;
  let repo: string;
  let home = "";

  beforeEach(async () => {
    // A no_offer enrichment: the hook still injects the local floor, which is what
    // makes INJECTED=true and therefore mints exactly one HOOK trace.
    intel = await startWire(JSON.stringify({ enrichment: { status: "no_offer", markdown: "" }, steps: [] }));
    stubDir = mkdtempSync(join(tmpdir(), "ml-actor-stub-"));
    repo = mkdtempSync(join(tmpdir(), "ml-actor-repo-"));
    writeFileSync(join(repo, ".meetless.json"), JSON.stringify({ workspaceId: WORKSPACE }));
  });

  afterEach(async () => {
    await intel.close();
    for (const d of [stubDir, repo, home]) {
      if (d) rmSync(d, { recursive: true, force: true, maxRetries: 20, retryDelay: 50 });
    }
    home = "";
  });

  function seed(actorUserId: string | null): string {
    // controlUrl points at a closed port on purpose: the detached flush is not
    // under test, and a refused connection keeps it out of the way while the
    // spool line -- the thing under test -- is still written.
    home = makeHome({
      controlUrl: "http://127.0.0.1:1",
      intelUrl: `http://127.0.0.1:${intel.port}`,
      mlaPath: makeMlaStub(stubDir, ["redact-capture", "assemble-context"]),
      actorUserId,
    });
    writeFileSync(join(home, "queue", `${SID}.workspaceId`), WORKSPACE);
    return home;
  }

  it("HOOK surface: spool_injection_trace stamps the configured actorUserId", async () => {
    seed(ACTOR);
    const r = await runHook(UPS_SH, home, {
      cwd: repo,
      input: JSON.stringify({ session_id: SID, prompt: "what governs error handling here" }),
      env: { MEETLESS_TURN_RECAP: "off" },
    });
    expect(r.status).toBe(0);

    const traces = injectionTraces(home);
    expect(traces.length).toBeGreaterThan(0);
    const hook = traces.find((t) => t.payload?.sourceSurface === "HOOK");
    expect(hook).toBeDefined();
    // The regression: this key was absent entirely, so control stored NULL.
    expect(hook!.payload).toHaveProperty("actorId");
    expect(hook!.payload.actorId).toBe(ACTOR);
  });

  it("MCP surface: a cited evidence pull stamps the configured actorUserId", async () => {
    seed(ACTOR);
    const r = await runHook(PTU_SH, home, {
      cwd: repo,
      input: JSON.stringify({
        session_id: SID,
        tool_name: "mcp__meetless__meetless__retrieve_knowledge",
        tool_input: { query: "error handling conventions" },
        tool_response: { candidates: [{ citation: "NT:notes/20260101-conventions.md" }] },
      }),
    });
    expect(r.status).toBe(0);

    const mcp = injectionTraces(home).find((t) => t.payload?.sourceSurface === "MCP");
    expect(mcp).toBeDefined();
    expect(mcp!.payload).toHaveProperty("actorId");
    expect(mcp!.payload.actorId).toBe(ACTOR);
  });

  it("logged out: actorId is an explicit null, never an empty string or a machine id", async () => {
    seed(null);
    const r = await runHook(UPS_SH, home, {
      cwd: repo,
      input: JSON.stringify({ session_id: SID, prompt: "what governs error handling here" }),
      env: { MEETLESS_TURN_RECAP: "off" },
    });
    expect(r.status).toBe(0);

    const hook = injectionTraces(home).find((t) => t.payload?.sourceSurface === "HOOK");
    expect(hook).toBeDefined();
    // Honest null. `""` would pass a `has("actorId")` check while naming nobody,
    // and a hashed machine id would be a DIFFERENT id space silently occupying a
    // column the console renders as "workspace member".
    expect(hook!.payload.actorId).toBeNull();
  });
});
