import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// The CLI half of the cross-repo byte-identity guard for the
// content-normalization corpus (ADR §3.3 / canonical model 5.2.2). The monorepo
// `packages/utils`, intel, and this CLI each vendor a byte-identical copy of the
// corpus and each hashes ITS copy against the SAME committed sha256 sidecar. No
// side reads another's file: the shared committed hash IS the contract. If any
// copy is edited without regenerating every sidecar, that repo's checksum test
// goes red. The canonical corpus + sidecar are regenerated by the monorepo
// `packages/utils/scripts/gen-content-normalization-corpus.ts`; the CLI copy is
// a byte-for-byte `cp` of the canonical `testdata/` pair.

const FIXTURES = join(__dirname, "..", "..", "fixtures", "content-normalization");
const CORPUS_PATH = join(FIXTURES, "content-normalization-corpus.json");
const SHA_PATH = join(FIXTURES, "content-normalization-corpus.sha256");

describe("content normalization corpus vendor-sync (CLI copy, cross-repo byte-identity)", () => {
  it("hashes the vendored corpus to the committed shared sha256 sidecar", () => {
    const bytes = readFileSync(CORPUS_PATH);
    const actual = createHash("sha256").update(bytes).digest("hex");
    const expected = readFileSync(SHA_PATH, "utf8").trim();
    expect(actual).toBe(expected);
  });
});
