// test/lib/scanner/managed-rules.spec.ts
//
// `.meetless/rules.md` is the mla-managed local file of a repo's durable governed rules
// (the backend rule store is the source of truth it is materialized from). These tests pin the
// invariants that make it trustworthy: stable content-derived ids, deterministic full-file
// render, idempotent re-attest, exact dedupe with source-merge, and lossless round-trip. The
// file is human-owned policy, so its directives are human_attested.
import {
  MANAGED_RULES_PATH,
  makeManagedRule,
  managedRuleId,
  upsertManagedRule,
  dedupeManagedRules,
  renderManagedRules,
  parseManagedRules,
  managedRulesToDirectives,
  type ManagedRule,
} from "../../../src/lib/scanner/managed-rules";

describe("managedRuleId", () => {
  it("is a stable 12-hex content hash of statement + kind + scope", () => {
    const id = managedRuleId("Use pnpm, not npm.", "RULE", []);
    expect(id).toMatch(/^[0-9a-f]{12}$/);
    expect(managedRuleId("Use pnpm, not npm.", "RULE", [])).toBe(id);
  });

  it("ignores whitespace differences in the statement (normalized first)", () => {
    expect(managedRuleId("  Use   pnpm,\tnot npm. ", "RULE", [])).toBe(
      managedRuleId("Use pnpm, not npm.", "RULE", []),
    );
  });

  it("is independent of scope order and duplicates", () => {
    expect(managedRuleId("x", "RULE", ["b/**", "a/**", "b/**"])).toBe(
      managedRuleId("x", "RULE", ["a/**", "b/**"]),
    );
  });

  it("differs when scope differs (a repo-wide rule is NOT the scoped rule)", () => {
    expect(managedRuleId("x", "RULE", [])).not.toBe(managedRuleId("x", "RULE", ["src/**"]));
  });
});

describe("makeManagedRule", () => {
  it("normalizes the statement, sorts/dedupes scope and sources, and defaults strength to SHOULD", () => {
    const r = makeManagedRule({
      statement: "  Prefer   relative imports ",
      scope: ["src/**", "src/**", "a/**"],
      sources: ["docs/x.md", "docs/x.md", "agent-memory:feedback_a.md"],
    });
    expect(r.statement).toBe("Prefer relative imports");
    expect(r.scope).toEqual(["a/**", "src/**"]);
    expect(r.sources).toEqual(["agent-memory:feedback_a.md", "docs/x.md"]);
    expect(r.strength).toBe("SHOULD_FOLLOW");
    expect(r.kind).toBe("RULE");
    expect(r.id).toBe(managedRuleId("Prefer relative imports", "RULE", ["a/**", "src/**"]));
  });

  it("keeps an explicit MUST_FOLLOW", () => {
    expect(makeManagedRule({ statement: "x", strength: "MUST_FOLLOW" }).strength).toBe("MUST_FOLLOW");
  });
});

describe("upsertManagedRule (idempotent + exact dedupe with source merge)", () => {
  it("re-attesting the identical rule is a structural no-op", () => {
    const r = makeManagedRule({ statement: "x", strength: "MUST_FOLLOW", sources: ["a"] });
    const once = upsertManagedRule([], r);
    const twice = upsertManagedRule(once, makeManagedRule({ statement: "x", strength: "MUST_FOLLOW", sources: ["a"] }));
    expect(twice).toEqual(once);
    expect(twice).toHaveLength(1);
  });

  it("merges a new source into the existing rule's evidence (exact dedupe)", () => {
    const a = upsertManagedRule([], makeManagedRule({ statement: "x", sources: ["docs/a.md"] }));
    const b = upsertManagedRule(a, makeManagedRule({ statement: "x", sources: ["docs/b.md"] }));
    expect(b).toHaveLength(1);
    expect(b[0].sources).toEqual(["docs/a.md", "docs/b.md"]);
  });

  it("promotes SHOULD to MUST but never demotes MUST to SHOULD", () => {
    const should = upsertManagedRule([], makeManagedRule({ statement: "x", strength: "SHOULD_FOLLOW" }));
    const promoted = upsertManagedRule(should, makeManagedRule({ statement: "x", strength: "MUST_FOLLOW" }));
    expect(promoted[0].strength).toBe("MUST_FOLLOW");
    const stillMust = upsertManagedRule(promoted, makeManagedRule({ statement: "x", strength: "SHOULD_FOLLOW" }));
    expect(stillMust[0].strength).toBe("MUST_FOLLOW");
  });

  it("treats a different scope as a different rule (no accidental merge)", () => {
    const wide = upsertManagedRule([], makeManagedRule({ statement: "x" }));
    const scoped = upsertManagedRule(wide, makeManagedRule({ statement: "x", scope: ["src/**"] }));
    expect(scoped).toHaveLength(2);
  });
});

describe("renderManagedRules / parseManagedRules round-trip", () => {
  const rules: ManagedRule[] = [
    makeManagedRule({ statement: "Use pnpm, not npm.", strength: "MUST_FOLLOW", sources: ["CLAUDE.md"] }),
    makeManagedRule({ statement: "Prefer relative imports", scope: ["src/**/*.ts"], sources: ["docs/x.md", "docs/y.md"] }),
    makeManagedRule({ statement: "Repo-wide advisory with no source" }),
  ];

  it("renders a stable, mla-owned file naming the backend as the source of truth in the header", () => {
    const out = renderManagedRules(rules);
    expect(out).toContain("GENERATED BY mla");
    expect(out).toContain("source of truth");
    expect(out).toContain("# Repository rules");
    expect(out.endsWith("\n")).toBe(true);
  });

  it("is byte-identical regardless of input order (deterministic ordering by id)", () => {
    expect(renderManagedRules(rules)).toBe(renderManagedRules([...rules].reverse()));
  });

  it("round-trips losslessly: parse(render(rules)) preserves every field", () => {
    const reparsed = parseManagedRules(renderManagedRules(rules));
    const norm = (rs: ManagedRule[]) => [...rs].sort((a, b) => a.id.localeCompare(b.id));
    expect(norm(reparsed)).toEqual(norm(rules));
  });

  it("writing the same rule set twice yields identical bytes (idempotent file)", () => {
    const first = renderManagedRules(rules);
    const second = renderManagedRules(parseManagedRules(first));
    expect(second).toBe(first);
  });

  it("renders repository-wide scope and an empty source list with readable placeholders", () => {
    const out = renderManagedRules([makeManagedRule({ statement: "x" })]);
    expect(out).toContain("- scope: (repository-wide)");
    expect(out).toContain("- sources: (none)");
  });

  it("recomputes id from content, ignoring a stale hand-edited bracket anchor", () => {
    const out = renderManagedRules([makeManagedRule({ statement: "real statement" })]);
    const tampered = out.replace(/## \[[0-9a-f]{12}\]/, "## [deadbeefdead]");
    const reparsed = parseManagedRules(tampered);
    expect(reparsed).toHaveLength(1);
    expect(reparsed[0].id).toBe(managedRuleId("real statement", "RULE", []));
  });

  it("tolerates a heading with no bracket anchor at all", () => {
    const reparsed = parseManagedRules("# Repository rules\n\n## A plain rule\n\n- strength: MUST_FOLLOW\n");
    expect(reparsed).toHaveLength(1);
    expect(reparsed[0].statement).toBe("A plain rule");
    expect(reparsed[0].strength).toBe("MUST_FOLLOW");
  });

  it("collapses two hand-written blocks that normalize to the same rule", () => {
    const text = [
      "# Repository rules",
      "",
      "## Use pnpm",
      "- sources: a.md",
      "",
      "## Use  pnpm", // same after whitespace normalization
      "- sources: b.md",
    ].join("\n");
    const reparsed = parseManagedRules(text);
    expect(reparsed).toHaveLength(1);
    expect(reparsed[0].sources).toEqual(["a.md", "b.md"]);
  });

  it("returns [] for an empty / headerless file", () => {
    expect(parseManagedRules("")).toEqual([]);
    expect(parseManagedRules("# Repository rules\n")).toEqual([]);
  });
});

describe("managedRulesToDirectives (INV-AUTH-1: managed rules are human_attested)", () => {
  it("maps every managed rule to a human_attested directive sourced from the managed file", () => {
    const dirs = managedRulesToDirectives([
      makeManagedRule({ statement: "Use pnpm, not npm.", strength: "MUST_FOLLOW" }),
    ]);
    expect(dirs).toHaveLength(1);
    expect(dirs[0].attestation).toBe("human_attested");
    expect(dirs[0].source).toBe(MANAGED_RULES_PATH);
    expect(dirs[0].kind).toBe("RULE");
    expect(dirs[0].strength).toBe("MUST_FOLLOW");
    expect(dirs[0].text).toBe("Use pnpm, not npm.");
  });

  it("carries scope through as directive globs, and omits globs for a repo-wide rule", () => {
    const [scoped] = managedRulesToDirectives([makeManagedRule({ statement: "x", scope: ["src/**"] })]);
    const [wide] = managedRulesToDirectives([makeManagedRule({ statement: "y" })]);
    expect(scoped.globs).toEqual(["src/**"]);
    expect(wide.globs).toBeUndefined();
  });

  it("reuses the stable rule id as the directive id", () => {
    const r = makeManagedRule({ statement: "x" });
    expect(managedRulesToDirectives([r])[0].id).toBe(r.id);
  });
});

describe("dedupeManagedRules", () => {
  it("folds a list with duplicate ids into one row, merging sources", () => {
    const out = dedupeManagedRules([
      makeManagedRule({ statement: "x", sources: ["a"] }),
      makeManagedRule({ statement: "x", sources: ["b"] }),
      makeManagedRule({ statement: "y" }),
    ]);
    expect(out).toHaveLength(2);
    const x = out.find((r) => r.statement === "x")!;
    expect(x.sources).toEqual(["a", "b"]);
  });
});
